WIP:Migrate/sdl
v3c70r/Muyo pull request #1
Opened 2021-04-10 23:32 UTC by xeechou

split window creation library.

2021-04-11 15:11 UTC, v3c70r commented
我稍微看了一下代码，brain dump 了一点想法

关于 SDL 支持

我认为我们应该支持 GLFW 或 SDL 而不是 GLFW 和 SDL， 所以用户在有这两个依赖之一的情况下都可以使用。为了达到这个目的，我们需要:
* 在编译时用 CMAKE 指定 `-DUSE_GLFW` 或者 `-DUSE_SDL`。如果用户指定的依赖不满足，则搜索另外一个依赖，若都不满足，报错。如果没有指定，则使用默认 GLFW （因为 GLFW 是一个 Submodule，我们自己可以 handle 编译，不需要用户本地安装)。
* 包含头文件时用 `-DUSE_GLFW` 或者 `-DUSE_SDL` 选择其一。
* 编译测试中应该加入 SDL 选项。我们现在主要在 Linux 和 Windows 上跑，所以我觉得得保证两个平台都没问题。不过 Windows　的编译测试我还没有写 🙁 
* 可能得加一个抽象中间层处理所有窗口相关的功能，（Surface type query, extension query, input handling, resizing, etc.)，理想状况是在 helloVulkan 中不需要 include 任何 GLFW 或者 SDL 头文件和相关函数。

Event library 我还没看 😛 ，不过 Event 的话以后可能会要考虑捕捉 Controller 的相关功能。

2021-04-12 01:48 UTC, xeechou commented
嗯，我当时的想法是先让渲染本身不依赖一一个窗口库，或者GLFW或者sdl或者qt都可以。我倾向于sdl是它支持wayland不需要重新编译，glfw要么编译成x11模式或者wayland模式，但是不能再runtime做选择。而且emscription对sdl有默认支持。

不过话说回来，如在这些库上再写一个兼容层就感觉有点奇怪了。一个兼容的方法是我们可以做一个app文件夹，把用glfw的main.cpp,和sdl的main.cpp放到不同的文件夹下面，这个操作和imgui的那些例子应该是一样的。这样的话用户可以跑hellovulkan SDL或者hellovulkanGLFW都可以。你看下这样搞行不行？

关于Windows的编译，我之前有写过一个cmake项目用来做协调，方法是在cmake目录下写针对不同平台的依赖和编译选项，这个我可以后来加进来。

那个event library应该还是挺好懂的，你一看估计就知道了😁

2021-04-20 02:51 UTC, v3c70r requested changes
Probably double check if everything compiles with MSVC. Sorry I don't have a proper test framework.

2021-04-20 02:51 UTC, v3c70r commented on CMakeLists.txt
>  if (NOT ${glfw3_FOUND})
Better with 
```
if (USE_SDL)
    find_package(SDL2 REQUIRED)
    ...
else()
   add_definition(-DUSE_GLFW)
   find_package(glfw3 3.2 QUIET)
   if (NOT ${glfw3_FOUND})
      ....
   endif()
endif()
```

2021-04-20 02:51 UTC, v3c70r commented on CMakeLists.txt
> +    "${CMAKE_CURRENT_LIST_DIR}/include"
We assume that our src is a flat structure and don't need to have an include folder.

2021-04-20 02:51 UTC, v3c70r commented on src/helloVulkan.cpp
> +    if (!Window::Init("hello Vulkan", WIDTH, HEIGHT))
```suggestion
    assert(Window::Init("hello Vulkan", WIDTH, HEIGHT) && "Failed to create window");
```

2021-04-20 02:51 UTC, v3c70r commented on src/helloVulkan.cpp
> +    // SDL_DestroyWindow(s_pWindow);
```suggestion
```

2021-04-20 02:51 UTC, v3c70r commented on .dir-locals.el
> +((c++-mode . ((eval . (c-set-offset 'innamespace 0))
Probably remove this file and add to `.gitignore`

2021-04-20 02:51 UTC, v3c70r commented on include/interface/key.h
> +enum ScanCode {
New line here before {, we are formatting with clang-format stype
```
            "AccessModifierOffset" : -4,
            "AllowShortIfStatementsOnASingleLine" : "true",
            "AlwaysBreakTemplateDeclarations" : "true",
            "Standard" : "C++11",
            "BreakBeforeBraces" : "Allman"}
```

2021-04-20 02:51 UTC, v3c70r commented on src/Event.h
> +    HandlerId m_Id;
It's just a unint32_t, no need to typedef it to another type. Also it's not representing a type, probably better with a `uint32_t`
```suggestion
    uint32_t m_nHandlerId;
```

2021-04-20 02:51 UTC, v3c70r commented on src/Event.h
> +    void emit(Args ... args)
Upper case function names. 
```suggestion
    void Emit(Args ... args)
```

2021-04-20 02:51 UTC, v3c70r commented on src/Event.h
> +    size_t m_Type;
Any reason to use size_t here? I think it's probably ok with uint32_t

2021-04-20 02:51 UTC, v3c70r commented on include/interface/key.h
> +    ScanCode_Invalid = 0,
Constant uses upper case.
```suggestion
    SCANCODE_INVALID = 0,
```

2021-04-20 02:51 UTC, v3c70r commented on src/Event.h
> +    //adding a
Remove

2021-04-20 02:51 UTC, v3c70r commented on src/Event.h
> +        for (HandlerType& handler : m_Collections) {
Does this iteration require lock? Or I guess we can remove the mutex for now as we don't really access them from multiple threads.

2021-04-20 02:51 UTC, v3c70r commented on include/interface/mouse.h
> +    Cursor_None = -1,
Same stuff, upper case for constants. 
```suggestion
    CURSOR_NONE = -1;
    ...
```

2021-04-20 02:51 UTC, v3c70r commented on src/Event.h
> +    //adding a
```suggestion
```

2021-04-20 02:51 UTC, v3c70r commented on src/EventSystem.h
> +    std::map<EventType, std::shared_ptr<EventBase>> m_Events;
Can it be unique_ptr? I assume this class manages the event resource. We can simply return a raw pointer when we want to access the event.

2021-04-20 02:51 UTC, v3c70r commented on src/WindowGLFW.h
> +static std::pair<int, int> GetWindowSize()
We have `VkExtent2D` for with height, no need to introduce a new type.

2021-04-20 02:51 UTC, v3c70r commented on src/WindowGLFW.h
> +static void Fini()
It's already confusing to have `Destroy*` and `Uninitialize*` as destruction functions. No need to introduce a new confusion.

2021-04-20 02:51 UTC, v3c70r commented on src/helloVulkan.cpp
> +                // SDL_GetWindowSize(s_pWindow, &width, &height);
```suggestion
```

2021-05-07 12:53 UTC, merged